CREATE TABLE products (
	id CHAR(32) NOT NULL,
	CODE VARCHAR(10),
	NAME VARCHAR(100) NOT NULL,
	PRICE DECIMAL(15,2),
	PRICE_CURRENCY CHAR(3),
	version INTEGER NOT NULL DEFAULT '0',
	PRIMARY KEY (id)
);